/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FelRouteImport } from './routes/fel'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedEquipmentRouteImport } from './routes/_authenticated/equipment'
import { Route as AuthenticatedCompareRouteImport } from './routes/_authenticated/compare'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedProspectsIndexRouteImport } from './routes/_authenticated/prospects/index'
import { Route as AuthenticatedProspectsProspectIdRouteImport } from './routes/_authenticated/prospects/$prospectId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FelRoute = FelRouteImport.update({
  id: '/fel',
  path: '/fel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipmentRoute = AuthenticatedEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompareRoute = AuthenticatedCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProspectsIndexRoute =
  AuthenticatedProspectsIndexRouteImport.update({
    id: '/prospects/',
    path: '/prospects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProspectsProspectIdRoute =
  AuthenticatedProspectsProspectIdRouteImport.update({
    id: '/prospects/$prospectId',
    path: '/prospects/$prospectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/fel': typeof FelRoute
  '/login': typeof LoginRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/compare': typeof AuthenticatedCompareRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/prospects/$prospectId': typeof AuthenticatedProspectsProspectIdRoute
  '/prospects/': typeof AuthenticatedProspectsIndexRoute
}
export interface FileRoutesByTo {
  '/fel': typeof FelRoute
  '/login': typeof LoginRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/compare': typeof AuthenticatedCompareRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/prospects/$prospectId': typeof AuthenticatedProspectsProspectIdRoute
  '/prospects': typeof AuthenticatedProspectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/fel': typeof FelRoute
  '/login': typeof LoginRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/compare': typeof AuthenticatedCompareRoute
  '/_authenticated/equipment': typeof AuthenticatedEquipmentRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/prospects/$prospectId': typeof AuthenticatedProspectsProspectIdRoute
  '/_authenticated/prospects/': typeof AuthenticatedProspectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fel'
    | '/login'
    | '/activity'
    | '/compare'
    | '/equipment'
    | '/settings'
    | '/prospects/$prospectId'
    | '/prospects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/fel'
    | '/login'
    | '/activity'
    | '/compare'
    | '/equipment'
    | '/settings'
    | '/'
    | '/prospects/$prospectId'
    | '/prospects'
  id:
    | '__root__'
    | '/_authenticated'
    | '/fel'
    | '/login'
    | '/_authenticated/activity'
    | '/_authenticated/compare'
    | '/_authenticated/equipment'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/prospects/$prospectId'
    | '/_authenticated/prospects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  FelRoute: typeof FelRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fel': {
      id: '/fel'
      path: '/fel'
      fullPath: '/fel'
      preLoaderRoute: typeof FelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipment': {
      id: '/_authenticated/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AuthenticatedEquipmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compare': {
      id: '/_authenticated/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AuthenticatedCompareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prospects/': {
      id: '/_authenticated/prospects/'
      path: '/prospects'
      fullPath: '/prospects/'
      preLoaderRoute: typeof AuthenticatedProspectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prospects/$prospectId': {
      id: '/_authenticated/prospects/$prospectId'
      path: '/prospects/$prospectId'
      fullPath: '/prospects/$prospectId'
      preLoaderRoute: typeof AuthenticatedProspectsProspectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedCompareRoute: typeof AuthenticatedCompareRoute
  AuthenticatedEquipmentRoute: typeof AuthenticatedEquipmentRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProspectsProspectIdRoute: typeof AuthenticatedProspectsProspectIdRoute
  AuthenticatedProspectsIndexRoute: typeof AuthenticatedProspectsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedCompareRoute: AuthenticatedCompareRoute,
  AuthenticatedEquipmentRoute: AuthenticatedEquipmentRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProspectsProspectIdRoute: AuthenticatedProspectsProspectIdRoute,
  AuthenticatedProspectsIndexRoute: AuthenticatedProspectsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  FelRoute: FelRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
